rules = [["incitement", "Act"],
["accessoryship", "Act"],
["Serious criminal offenses", "Act"],
["Less serious criminal offenses", "Act"],
["crime", "Act"],
["attempt", "Act"],
["unlawful act", "Act"],
["serious criminal offense attempt", "Act"],
["mistake", "Act"],
["slanderous insults", "Act"],
#~ ["if",  "Func"],
#~ ["then",  "Func"],
["else if",  "Func"],
#~ ["or",  "Func"],
#~ ["and",  "Func"],
["only if",  "Func"],
["law","Law"],
["German Criminal Law","Law"],
["international conventions on the protection of the sea","Law"],
["penal norm","Law"],
["provisions of the General Part","Law"],
["international agreement","Law"],
["more lenient norm","Law"],
["Extradition Act","Law"],
["no criminal law enforcement","Law"],
["German law","Law"],
["provisions","Law"],
["underlying factual findings","Law"],
["offence","Law"],
["Statutory provisions","Law"],
["no part to the contribution","Law"],
["limits of necessary defense","Law"],
["Jvenile Court Law","Law"],
["nature of the object","Law"],
["legal order","Law"],
["one of the applicable norms","Law"],
["Punishablity","punishability"],
["wrongfulness","punishability"],
["Judgement","Judgement"],
["placement in a psychiatric hospital","Judgement"],
["withdrawal of permission to drive","Judgement"],
["Imprisonment","Judgement"],
["fine","Judgement"],
["Aggravation","Judgement"],
["mitigation","Judgement"],
["minimum of a lesser term of imprisonment","Judgement"],
["punishment","Judgement"],
["domestically","Location"],
["in the territorial area","Location"],
["in Germany","Location"],
["abroad","Location"],
["place","Location"],
["his livelihood","Attribute"],
["his duties","Attribute"],
["characteristics","Attribute"],
["voluntarily","Attribute"],
["Federal Republic of Germany","Organization"],
["business","Organization"],
["agency","Organization"],
["their committees","Organization"],
["Bundestag  -LRB- Federal Parliament -RRB-","Organization"],
["Federal Assembly","Organization"],
["legislative body of a Land  -LRB- constituent state -RRB-","Organization"],
["enterprise ","Organization"],
["court ","Organization"],
["bodies","Organization"],
["commercial partnership","Organization"],
["other German agency","Organization"],
["whoever","Person"],
["perpetrator","Bob"],
["inciter","Bob"],
["accessory","Bob"],
["convicted person","Bob"],
["relative","John"],
["legal person","John"],
["statutory representative","John"],
["proceeding","Proceeding"],
["time","Time"],
["request for extradition","NPA"],
["Circumstances","Circumstance"],
["danger","Circumstance"],
["imminent danger","Circumstance"],
["guilt","Fault"],
["right to elect or vote in public matters","Law"],
["driving ban","Judgement"],
["term of prohibition","Judgement"],
["one daily rate","Judgement"],
["one day imprisonment","Judgement"],
["aggregate punishment","Judgement"],
["custody","Judgement"],
["term of the prohibition","Judgement"],
["instalment in time","Judgement"],
["to pay in specified instalments","Judgement"],
["payment deadline","Judgement"],
["property fine","Judgement"],
["imprisonment for life","Judgement"],
["federal flag","Object"],
["national insignia","Object"]]
